### ISSUE TITLE
pitch conditions as input parameter

### ISSUE THREAD

**Issue by mramesh443** [Jamee999/cricket#21]
new to python and github here, stumbled upon ur gem here. i wanted a scenario where in i cud take ground conditions as input like 1. rank turner of Chepauk 2. green seamer of Lords 3. bouncy devil of Waca. so that we can control the spin and seam factor as an input parameter.

**Comment by YuvrajSingh01** [comment]
I suppose you can do that, only you need to change  a few lines in callcricketnew.py
`def pitchmake (Weather):
	PaceFactor = 1 + (0.3*random.random()) * (random.random()-random.random()) #how good the pitch is for pace. 0.75-1.25, lower is better for bowling
	SpinFactor = 1 + (0.3*random.random()) * (random.random()-random.random()) #same for spin
`
Line no. 83.

**Comment by Jamee999** [comment]
I've been thinking about something like this. I just worry about making it too much user input in the terminal. Perhaps I could make a "settings" file, where you could just set Pace = 1.25 in the file and it would automatically apply.

**Comment by mramesh443** [comment]
> I've been thinking about something like this. I just worry about making it too much user input in the terminal. Perhaps I could make a "settings" file, where you could just set Pace = 1.25 in the file and it would automatically apply.

yeah, also there are like three distinct variables here. Bounce(Oz), Seam(english) and Spin(asia). Any chance in future u r thinking about incorporating the bounce factor as well ? Also, many thanks for the game mate, it is tremendous n a crckt fans' delight. Cheers :)

**Comment by Jamee999** [comment]
At the moment there are only two variables in the sim - how favorable it is for fast/medium bowlers, and how good it is for spinners. I'd definitely like a more sophisticated system at some point.

**Comment by mramesh443** [comment]
> At the moment there are only two variables in the sim - how favorable it is for fast/medium bowlers, and how good it is for spinners. I'd definitely like a more sophisticated system at some point.

it is perfect in its current form, what i suggested was an enhancement which wud take the game to another level. Also, as the game progresses on will the spin factor detoriate making it difficult to face the spinners and batting becomes difficult in general? coz i remember seeing in many of the sims that the second inns spin factor is always high the first innings one meaning facing spinners is easy, no?

**Comment by Jamee999** [comment]
Yeah, the pitch deteriorates throughout the game. So fast bowling is relatively stronger on the first day, and spin bowling on the fifth day.

**Comment by mramesh443** [comment]
but the 

> Yeah, the pitch deteriorates throughout the game. So fast bowling is relatively stronger on the first day, and spin bowling on the fifth day.

but the spin factor at the end of the game and the beginning of the game generally throws up confusing numbers, like at the start of the game 0.75 and at the end 1.11. Shouldn't it be the opposite way?

**Comment by Jamee999** [comment]
The spin factor and pace factor shouldn't change throughout the game.

**Comment by mramesh443** [comment]
> but the
> 
> > Yeah, the pitch deteriorates throughout the game. So fast bowling is relatively stronger on the first day, and spin bowling on the fifth day.
> 
> but the spin factor at the end of the game and the beginning of the game generally throws up confusing numbers, like at the start of the game 0.75 and at the end 1.11. Shouldn't it be the opposite way?

Enter number of games to be played: 1
Pace Factor: 0.75 Spin Factor: 0.75
.....
 Australia (137, 263-4) beat India (161, 237) by 6 wickets.
 Man of the Match: SR Waugh (Australia) (30, 63, 4-15, 2-5)
 Pace Factor: 0.75, Spin Factor: 1

 India 0 Australia 1 Draw 0

**Comment by mramesh443** [comment]
> The spin factor and pace factor shouldn't change throughout the game.
0.75 is the least value which we must set to make it a dustbowl(absolute turning track) ?

**Comment by Jamee999** [comment]
I will look into that - it seems like a bug. Lower is more bowler-friendly, yes.

**Comment by Jamee999** [comment]
Found the issue. Looks like it was cosmetic, rather than actually affecting gameplay - the spin factor at the bottom was wrong. Will fix shortly.

**Comment by mramesh443** [comment]
> I will look into that - it seems like a bug. Lower is more bowler-friendly, yes.

i got that part from the comment in the code, but what if i set the spin factor to say 0.5, will the algo make the pitch more spiteful and help the spinners even more than what it wud be 0.75 or 0.75 is the least value ?

**Comment by mramesh443** [comment]
> Found the issue. Looks like it was cosmetic, rather than actually affecting gameplay - the spin factor at the bottom was wrong. Will fix shortly.

that was quick :) if it doesnt impact the gameplay, then cool with it.

**Comment by Jamee999** [comment]
The spin factor at the bottom of the scorecard was being rounded to the nearest whole number, rather than to two decimal places, because of a misplaced bracket.

**Comment by Jamee999** [comment]
You can set the spin value to whatever you want, you'll just get more extreme results.

**Comment by mramesh443** [comment]
> You can set the spin value to whatever you want, you'll just get more extreme results.

awesome that is what i exactly want, i am overseeing a draft where in the criteria is the pitches will be raging turners and green mambas, so i need extreme conditions to sim my team. thanks a ton mate, u r a superstar, this code works like a charm :)
