### ISSUE TITLE
Creating custom teams

### ISSUE THREAD

**Issue by gruzzly42** [Jamee999/cricket#22]
Hi - amazing work. Is it possible to explain how the customteams.txt file is formatted so I can understand how to create my own teams?

**Comment by Jamee999** [comment]
Name
Batting Average
Bowling Average
Role
First Year
Last Year
Batting strike Rate modifier (1 is average, higher is quicker)
Economy Rate modifier (1 is average, higher is more expensive)
Number of Tests captained
