### ISSUE TITLE
No weather delays when running custom game

### ISSUE THREAD

**Issue by ak472112** [Jamee999/cricket#24]
Would love there to be a way for there to be weather delays in custom games. Would also be great if you could choose what ground each match is at. 

Sorry am very new to python and coding and there probably is a way to do it myself but I can't figure it out. 

Am a massive massive fan of this programme. Has made mine and my mates lockdown so much better! Thanks a lot in advance

**Comment by Jamee999** [comment]
This is on my to-do list. Thanks for the kind words.

**Comment by Jamee999** [comment]
Version 2.2 has a "settings.txt" file in which things like this can be customised.

**Comment by ak472112** [comment]
How do i insert this into the python programme? Sorry am very new to this!

**Comment by Jamee999** [comment]
Re-download the files from the directory. The updated version will now read from the "settings.txt" file. You just need to edit the file (in any text-editing program) to match the settings you want. There are instructions in the file.
