### ISSUE TITLE
Role not defined

### ISSUE THREAD

**Issue by lepisma** [Jamee999/cricket#5]
```
Traceback (most recent call last):
  File "cricket.py", line 1718, in <module>
    innings (BatTeam)
  File "cricket.py", line 1500, in innings
    over (i)
  File "cricket.py", line 1337, in over
    Dismissal = Wicket (Bat1, Bowl1)
  File "cricket.py", line 1176, in Wicket
    if random.random() > 0.9 and ('Med' in Role or 'Spin' in Role):
NameError: name 'Role' is not defined
```

Maybe some variable name issue.

PS: This simulator is fun! Where did you get the team data from?

**Comment by Jamee999** [comment]
I think that the version of cricket.py I just uploaded should fix this. I accidentally had one "role" and one "Role" and python doesn't like that.

The player data is all scraped from cricinfo player pages, and then the program selects the two teams based on players whose careers included the specified year or years.
